poetry_app/art/forms.py
"""
File:  art/forms.py
Author:  Kati Kimble
Date: 09-June-2024

File Description:
- Defines FlaskForm class using WTForms for handling form validation and rendering.
"""

from flask_wtf import FlaskForm
from wtforms import StringField, FileField, SubmitField
from wtforms.validators import DataRequired


class UploadArtForm(FlaskForm):
    title = StringField('Title:', validators=[DataRequired()])
    art_upload = FileField('Upload Art:', validators=[DataRequired()])
    submit = SubmitField('Upload')

poetry_app/art/views.py
"""
File:  art/views.py
Author:  Kati Kimble
Date: 09-June-2024

File Description:
- Defines the Views for Art.
"""

from flask import Blueprint, render_template
from poetry_app.models import Art

# Create a new Blueprint for the 'art' section
art = Blueprint('art', __name__, static_url_path='/art/static', template_folder='templates/art',
                              static_folder='static')


# Define the route for the 'art_gallery' page
# This route will handle requests to the '/art_gallery' URL
@art.route('/art_gallery')
def art_gallery():
    arts = Art.query.order_by(Art.date_posted.desc()).all()
    return render_template('art.html', arts=arts)


# This route will handle requests to the '/art_detail' URL
@art.route('/art/<int:art_id>')
def art_detail(art_id):
    art_work = Art.query.get_or_404(art_id)
    return render_template('art_detail.html', art=art_work)

poetry_app/art/templates/art/art.html
{% extends "layout.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('art.static', filename='styles/art.css') }}">
<div class="container">
    <div class="row">
        {% for art in arts %}
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img class="card-img-top fixed-size-img" src="{{ url_for('static', filename='uploads/' ~ art.art_upload) }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ art.title }}</h5>
                        <a href="{{ url_for('art.art_detail', art_id=art.id) }}" class="view-button">View</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

poetry_app/art/templates/art/art_detail.html
{% extends "layout.html" %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('art.static', filename='styles/art.css') }}">
<div class="container">
    <div class="art-detail-container">
        <img src="{{ url_for('static', filename='uploads/' ~ art.art_upload) }}" class="img-fluid" alt="{{ art.title }}" style="max-width: 100%; height: auto; display: block;">
    </div>
    <button id="back-button" class="back-button" onclick="goBack()">Back</button>
</div>

<script>
    function goBack() {
        window.history.back();
    }
</script>
{% endblock %}