poetry_app/about/views.py
"""
File:  about/views.py
Author:  Kati Kimble
Date: 09-June-2024

File Description:
- Defines the Views for About.
"""

from flask import Blueprint, render_template
from poetry_app.models import AboutMe

# Create a new Blueprint for the 'about' section
about_bp = Blueprint('about', __name__, static_url_path='/about/static', template_folder='templates/about',
                              static_folder='static')

# Define the route for the 'about' page
# This route will handle requests to the '/about' URL
@about_bp.route('/about')
def about():
    # Query the AboutMe table to get the first entry
    about_me_entry = AboutMe.query.first()
    # Extract the content from the entry, or provide a default message if no entry exists
    about_me_content = about_me_entry.content if about_me_entry else "No content available."
    # Render the 'about_me.html' template and pass the content to it
    return render_template('about_me.html', about_me_content=about_me_content)

poetry_app/art/views.py
"""
File:  art/views.py
Author:  Kati Kimble
Date: 09-June-2024

File Description:
- Defines the Views for Art.
"""

from flask import Blueprint, render_template
from poetry_app.models import Art

# Create a new Blueprint for the 'art' section
art = Blueprint('art', __name__, static_url_path='/art/static', template_folder='templates/art',
                              static_folder='static')


# Define the route for the 'art_gallery' page
# This route will handle requests to the '/art_gallery' URL
@art.route('/art_gallery')
def art_gallery():
    arts = Art.query.order_by(Art.date_posted.desc()).all()
    return render_template('art.html', arts=arts)


# This route will handle requests to the '/art_detail' URL
@art.route('/art/<int:art_id>')
def art_detail(art_id):
    art_work = Art.query.get_or_404(art_id)
    return render_template('art_detail.html', art=art_work)

poetry_app/poems/views.py
"""
File:  poems/views.py
Author:  Kati Kimble
Date: 09-June-2024

File Description:
- Defines the Views for Poems.
"""

from flask import Blueprint, render_template
from poetry_app.models import Poem

# Create Poems blueprint
poems_bp = Blueprint('poems', __name__, static_url_path='/poems/static', template_folder='templates/poems',
                              static_folder='static')


# Route for Poems page
@poems_bp.route('/poems')
def poems():
    poetry = Poem.query.order_by(Poem.date_posted.desc()).all()
    return render_template('poems.html', poems=poetry)

poetry_app/templates/layout.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}Brittani Wrote This</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='content', height=400) }}
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/main.css') }}">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:ital,opsz,wght@0,6..96,400..900;1,6..96,400..900&family=Cormorant+Upright:wght@300;400;500;600;700&family=DotGothic16&family=Nixie+One&family=Oxygen+Mono&family=Syne+Mono&display=swap" rel="stylesheet">
</head>
<body class="home-color">
<div class="top-banner">
        Brittani Wrote This

    <div class="banner">
        Poetry & Art by Brittani Collette
    </div>
</div>

    <div id="mySidebar" class="sidebar">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="{{ url_for('about.about') }}">Bio</a>
        <a href="{{ url_for('poems.poems') }}">Poems</a>
        <a href="{{ url_for('art.art_gallery') }}">Art</a>
        <a href="{{ url_for('contact.contact') }}">Contact</a>
        <a href="{{ url_for('subscribe.handle_subscribe') }}">Subscribe</a>
        <a href="{{ url_for('admin.login') }}">Admin</a>
    </div>

    <div id="main">
        <button class="openbtn" onclick="openNav()">&#9776; Menu</button>
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
    </div>

    <script>
      function openNav() {
        document.getElementById("mySidebar").style.width = "250px";
        document.getElementById("main").style.marginLeft = "250px";
      }

      function closeNav() {
        document.getElementById("mySidebar").style.width = "0";
        document.getElementById("main").style.marginLeft= "0";
      }
    </script>
</body>
</html>